# runtime: custom
# env: flex

# manual_scaling:
#   instances: 1

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# handlers:
# - url: /.*
#   script: auto
#   secure: always

# env_variables:
#   FLASK_APP: api/main
#   GUNICORN_CMD_ARGS: '--bind=0.0.0.0:8080 --workers=1 --threads=8 app:app'

# entrypoint: gunicorn -b :8080 api.main:app



