runtime: python39
# env: flex
instance_class: F1

handlers:
# frontend
- url: /static
  static_dir: build/static
- url: /(.*\.(json|ico|js|html))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|html)$

# backend
- url: /.*
  script: api.main.app
# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: auto\

# handlers:
# - url: /api/.*
#   script: auto
# entrypoint: cd api && gunicorn -b :$PORT main:app
# entrypoint: cd api
# runtime_config:
#   operating_system: ubuntu22
