
runtime: python39

entrypoint: gunicorn -b :$PORT main:app
env_variables:
  FLASK_APP: "main"
  FLASK_ENV: "production"

handlers:
  # - url: /static
  #   static_dir: build/static

  - url: /static/css
    static_dir: build/static/css
  - url: /static/js
    static_dir: build/static/js

  - url: /api/.*
    script: auto
  - url: /.*
    secure: always
    script: auto


