# runtime: python39

# entrypoint: gunicorn -b :$PORT api.main:app
# env_variables:
#   FLASK_APP: "main"
#   FLASK_ENV: "production"
#   GUNICORN_CMD_ARGS: "--timeout 60 --workers 1 --threads 8"

# handlers:
#   - url: /static
#     static_dir: api/build/static
#   - url: /.*
#     script: auto
#     secure: always
#   - url: /api/.*
#     script: auto
#     secure: always

runtime: python39

entrypoint: gunicorn -w 1 -t 60 -b :$PORT api.main:app
env_variables:
  FLASK_APP: "main"
  FLASK_ENV: "production"

handlers:
  - url: /static
    static_dir: api/build/static
  - url: /api/.*
    script: auto
  - url: /.*
    secure: always
    script: auto


