runtime: python39

entrypoint: gunicorn -b :8080 api.main:app
env_variables:
  FLASK_APP: "api/main"
  FLASK_ENV: "production"
  GUNICORN_CMD_ARGS: "--timeout 60 --workers 1 --threads 8"

handlers:
  - url: /static
    static_dir: build/static
  - url: /.*
    script: auto
    secure: always
  - url: /api/.*
    script: auto
    secure: always



